apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferencePool
metadata:
  name: vllm-smol
  namespace: default
spec:
  targetPortNumber: 8000
  selector:
    app: vllm-smol
  extensionRef:
    name: vllm-smol-epp
    portNumber: 9002
